export const ASYNC_REQUEST = 'ASYNC_REQUEST';
export const DECREMENT = 'DECREMENT';
export const INCREMENT = 'INCREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';

export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';
export const USER_RECEIVED = 'USER_RECEIVED';
